
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modales.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Reportes
{

    public int idReporte { get; set; }

    public string nombreCliente { get; set; }

    public int idEquipo { get; set; }

    public int idPruebaElectrica { get; set; }

    public int idPruebasFisicas { get; set; }

    public int idPruebaQuimica { get; set; }

    public int idPruebaCroma { get; set; }

    public string fechaReporte { get; set; }

    public string escritor { get; set; }

    public string muestreador { get; set; }

    public string obsevacion { get; set; }

}

}
