
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modales.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Clientes
{

    public string NombreCliente { get; set; }

    public string Contacto { get; set; }

    public string Direccion { get; set; }

    public int Telefono { get; set; }

    public string Email { get; set; }

    public string Proyecto { get; set; }

}

}
