
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Modales.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_Historial
{

    public int idRegistro { get; set; }

    public string Registro { get; set; }

    public string Usuario { get; set; }

    public string Fecha { get; set; }

}

}
